detailpage/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'detail'

urlpatterns = [
    path('<int:id>', views.get_detail, name="detailpage"),
]

urlpatterns += staticfiles_urlpatterns()

googleplaystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="home"),
    path('detail/', include('detailpage.urls'), name="detail"),
]

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
    path('search', views.search, name="search"),
]

urlpatterns += staticfiles_urlpatterns()

detailpage/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=255)

detailpage/views.py
from qwikidata.sparql import (get_subclasses_of_item,
                              return_sparql_query_results)
from qwikidata.entity import WikidataItem, WikidataLexeme, WikidataProperty
from qwikidata.linked_data_interface import get_entity_dict_from_api
from django.shortcuts import render
from SPARQLWrapper import SPARQLWrapper, JSON

WD_PROPS = [
    'wdt:P571', # Inception time
    'wdt:P1705', # Native label
    'wdt:P112', # Founder(s)
    'wdt:P17', # Country
    'wdt:P159', # Headquarters Location
    'wdt:P123', # Publisher
    'wdt:P750', # Distributor(s)
    'wdt:P137', # Operator
    'wdt:P178', # Developer
    'wdt:P400', # Platform(s)
    'wdt:P277', # Programming Language(s)
    'wdt:P1324', # Source code URL
    'wdt:P348', # Software version
    'p:P154', 
]

def get_detail(request, id):
    result = query_details(id)
    wikidata = result[1]
    if len(result[1]) == 0:
      wikidata = 0
    return render(request, 'detailpage.html', {'local': result[0], 'wikidata': wikidata, 'name': result[0]['AppName'][0]})

def queryGraph(query_str):
    sparql = SPARQLWrapper("http://localhost:9999/blazegraph/sparql")
    sparql.setQuery(query_str)
    sparql.setReturnFormat(JSON)
    return sparql.query().convert()

def query_details_local(id):
    sparql_query = '''
    prefix ns1: <http://googleplaystore.org/app/>

    SELECT ?prop ?obj
    WHERE {
        ns1:%s ?prop ?obj.
    }
    ''' % id

    res = queryGraph(sparql_query)
    claims = {}
    for claim in res['results']['bindings']:
        prop = claim['prop']['value'].split('/')[-1][3:]
        obj = claim['obj']['value']
        if prop not in claims:
            claims[prop] = []
        claims[prop].append(obj)
    return claims

def get_interesting_props():
    tmp = ','.join(WD_PROPS)
    return f'({tmp})'

def query_details_wikidata(query_name):
    wd_query = (
        'SELECT DISTINCT ?propLabel ?objLabel ' +
        'WHERE ' +
        '{ ' +
        '{ ?app wdt:P31 wd:Q620615. }' +
        'UNION' +
        '{ ?app wdt:P306 wd:Q94. }' +
        ' ' +
        '?app rdfs:label ?appLabel. ' +
        'FILTER(LANG(?appLabel) = "en"). ' +
        f'FILTER(CONTAINS(?appLabel, "{query_name}")). ' +
        ' ' +
        '?app ?prop ?obj. ' +
        '?claim wikibase:directClaim ?prop. ' +
        '?claim rdfs:label ?propLabel. ' +
        'FILTER(LANG(?propLabel) = "en"). ' +
        f'FILTER(?prop IN {get_interesting_props()}).'
        ' ' +
        '?obj rdfs:label ?objLabel. ' +
        'FILTER(LANG(?objLabel) = "en"). ' +
        '}'
    )
    
    raw_res = return_sparql_query_results(wd_query)
    search_res = raw_res['results']['bindings']
    claims = {}
    for claim in search_res:
        propLabel = claim['propLabel']['value']
        objLabel = claim['objLabel']['value']
        if propLabel not in claims:
            claims[propLabel] = []
        claims[propLabel].append(objLabel)
    return claims

def query_details(id):
    data_local = query_details_local(id)

    app_name = data_local['AppName'][0].split(" ")[0]
    data_wd = query_details_wikidata(app_name)

    return (data_local, data_wd)

homepage/views.py
from django.shortcuts import render
from SPARQLWrapper import SPARQLWrapper, JSON
from .forms import SearchForm

ALLOWED_KEYS = ['name', 'category', 'type', 'genre']
CAPITALIZED = ['name', 'type', 'genre']
ALL_CAPS = ['category']

def home(request):
    form = SearchForm()
    return render(request, 'homepage.html', {'form': form})

def search(request):
    if request.method == 'POST':
        # query_str = request.POST.get('query', '')
        query_str = SearchForm(request.POST)['search'].value()
        if query_str != '':
            query_keypair = parseQuery(query_str)
        else:
            query_keypair = {}
    else:
        query_str = ''
        query_keypair = {}

    result = queryGraph(query_keypair)
    if(len(result['results']['bindings']) == 0):
      result = 0

    return render(request, 'search.html', {'result' : result, 'query_str' : query_str})

def queryGraph(query_keypair):
    sparql = SPARQLWrapper("http://localhost:9999/blazegraph/sparql")
    sparql.setQuery(buildQuery(query_keypair))
    sparql.setReturnFormat(JSON)
    return sparql.query().convert()

def buildQuery(query_keypair):
    filter = ''
    for key in query_keypair.keys():
        filter = filter + 'filter(regex(?%s, "%s", "i")) .' % (key, query_keypair[key])
    if filter != '': 
        filter = filter[:-1] + '.'
    
    sparql_query = '''
    prefix ns1: <http://googleplaystore.org/>

    SELECT ?app ?id ?name ?category ?type ?genre
    WHERE {
        ?app ns1:hasId ?id ;
             ns1:hasAppName ?name ;
             ns1:hasCategory ?category ;
             ns1:hasType ?type ;
             ns1:hasGenre ?genre .
        %s
    }
    ''' % filter
    
    print(sparql_query)

    return sparql_query

def parseQuery(query_str):
    query_keypair = {}

    keypairs = query_str.split(';')
    for keypair in keypairs:
        split_keypair = keypair.split(':')
        key = split_keypair[0]
        value = ' '.join(split_keypair[1:])
        if key not in ALLOWED_KEYS:
            continue
        
        query_keypair[key] = formatValue(key, value)
    
    return query_keypair

def formatValue(key, value):
    if key in CAPITALIZED:
        return value.capitalize()
    if key in ALL_CAPS:
        return value.upper()
    return value

detailpage/templates/detailpage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>G App List</title>
</head>
<body class="m-4">
  <div class="d-flex mx-5 pb-3 align-items-center border-bottom justify-content-between" style="border-color: #347cdb!important; border-width: 2px!important;">
    <a href="{% url 'home:home' %}">
      <h1 class="text-center m-0" style="color: #26538d;">G App List</h1>
    </a>
    <div class="d-flex align-items-center ml-4">
      <form action="{% url 'home:search' %}" method="POST">
        {% csrf_token %}
        <div class="d-flex">
          <div class="form-group m-0" style="width: 800px;">
              <input name="search" type="text" class="form-control" placeholder="Cari Aplikasi (contoh: name:Discord;genre:Communication)" maxlength="255">
          </div>
          <div class="d-flex justify-content-center ml-2 my-0">
            <button class="btn btn-primary" id="search_button" style="height: 38px;">Search</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="px-5">
    <h3 style="margin-top: 36px; color: #347cdb;">{{name}}</h3>
    <h5 style="margin-top: 28px;">Informasi mengenai aplikasi (Berdasarkan local RDF store)</h5>
    <div class="" style="display:grid;grid-template-columns: repeat(2, minmax(0, 1fr));">
      {% for key, values in local.items %}
        <div class="border py-2 pl-2">
          <p class="m-0" style="font-weight: bold;">{{key}}</p>
        </div>
        <div class="border py-2 pl-2">
          <p class="m-0">
            {% for value in values %}
              {% if key == 'hasPrice' and value != '0.0' %}
                ${{value}} <br>
              {% else %}
                {{value}} <br>
              {% endif %}
            {% endfor %}
          </p>
        </div>
      {% endfor %}
    </div>
    <h5 style="margin-top: 40px;">Informasi mengenai aplikasi (Berdasarkan Wikidata)</h5>
    {% if wikidata != 0 %}
      <div class="" style="display:grid;grid-template-columns: repeat(2, minmax(0, 1fr));">
        {% for key, values in wikidata.items %}
          <div class="border py-2 pl-2">
            <p class="m-0" style="font-weight: bold; text-transform: capitalize;">{{key}}</p>
          </div>
          <div class="border py-2 pl-2">
            <p class="m-0">
              {% for value in values %}
                {{value}} <br>
              {% endfor %}
            </p>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>Tidak ada informasi mengenai aplikasi ini dari Wikidata.</p>
    {% endif %}
  </div>
</body>
</html>

homepage/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>G App List</title>
</head>
<body class="m-4">
  <div class="d-flex justify-content-center flex-column px-5 " style="width: 1200px; height: 100vh;">
    <a href="{% url 'home:home' %}">
      <h1 class="text-center" style="color: #26538d;">G App List</h1>
    </a>
    <div>
      <form class="mt-5" action="{% url 'home:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="search" type="text" class="form-control" placeholder="Cari Aplikasi (contoh: name:Discord;genre:Communication)" maxlength="255">
        </div>
        <div class="d-flex justify-content-center">
          <button class="btn btn-primary" id="search_button">Search</button>
        </div>
      </form>
      <div class="mt-5">
        <h5>Panduan Melakukan Pencarian:</h5>
        <p>
          Pencarian dapat dengan menuliskan input dengan beberapa keyword(minimal 1 keyword):
          <br>
          - "name:", bagian ini untuk mencari aplikasi-aplikasi dengan nama yang dimasukkan.
          <br>
          - "category:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan kategori sesuai input yang dimasukkan.
          <br>
          - "type:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan tipe sesuai input yang dimasukkan.
          <br>
          - "genre:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan genre sesuai input yang dimasukkan.
        </p>
      </div>
    </div>
  </div>
</body>
</html>

homepage/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>G App List</title>
</head>
<body class="m-4">
  <div class="d-flex justify-content-center flex-column px-5 " style="width: 1200px">
    <a href="{% url 'home:home' %}">
      <h1 class="text-center" style="color: #26538d;">G App List</h1>
    </a>
    <div>
      <form class="mt-5" action="{% url 'home:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="search" type="text" class="form-control" placeholder="Cari Aplikasi (contoh: name:Discord;genre:Communication)" maxlength="255">
        </div>
        <div class="d-flex justify-content-center">
          <button class="btn btn-primary" id="search_button">Search</button>
        </div>
      </form>
      <div class="mt-5">
        <h5>Panduan Melakukan Pencarian:</h5>
        <p>
          Pencarian dapat dengan menuliskan input dengan beberapa keyword(minimal 1 keyword):
          <br>
          - "name:", bagian ini untuk mencari aplikasi-aplikasi dengan nama yang dimasukkan.
          <br>
          - "category:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan kategori sesuai input yang dimasukkan.
          <br>
          - "type:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan tipe sesuai input yang dimasukkan.
          <br>
          - "genre:", bagian ini untuk melakukan pencarian aplikasi-aplikasi dengan genre sesuai input yang dimasukkan.
        </p>
      </div>
    </div>
  </div>
  <h3 class="px-5" style="margin-top: 48px; color:#347cdb">Hasil Pencarian Dari "{{query_str}}":</h3>
  {% if result != 0 %}
    <div class="px-5" style="display:grid;grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 1rem;">
      {% for app in result.results.bindings %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{app.name.value}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Genre aplikasi: {{app.genre.value}}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Kategori aplikasi: {{app.category.value}}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Tipe aplikasi: {{app.type.value}}</h6>
            <a class="card-link" href="{% url 'detail:detailpage' app.id.value %}">
              Lihat detail
            </a>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  {% else %}
    <p class="px-5">Tidak ada aplikasi yang ditemukan.</p>
  {% endif %}
</body>
</html>